name: Mobile Live Update

on:
  workflow_dispatch:

jobs:
  live-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check for native code changes
        id: check_native_changes
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          git fetch origin main

          LAST_SUCCESS_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/mobile-live-update.yaml/runs?status=success&branch=main&per_page=1" \
            | jq -r '.workflow_runs[0].head_sha')

          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit: $CURRENT_COMMIT"
          echo "Last successful SHA: $LAST_SUCCESS_SHA"

          if [ -n "$LAST_SUCCESS_SHA" ] && [ "$LAST_SUCCESS_SHA" != "null" ]; then
            NATIVE_CHANGES=$(git diff --name-only $LAST_SUCCESS_SHA $CURRENT_COMMIT | grep -E '^(ios/|android/)')
          else
            echo "No previous successful run found, proceeding with live update"
            NATIVE_CHANGES=""
          fi

          if [ -n "$NATIVE_CHANGES" ]; then
            echo "::warning::Native code changes detected since last deployment. Stopping workflow."
            echo "::error::Cannot proceed with live update due to native code changes. Please release a new app version."
            exit 1
          else
            echo "No native code changes detected. Proceeding with live update."
          fi

      - name: Ship Live Update bundle 🚀
        run: |
          echo "Build done"
